permalink: /:slug
theme_config:
  appearance: auto
  date_format: '%B %d %Y'
# exclude:
  # - 
highlighter: rouge
sass:
  style: ':compressed'
plugins:
  - jekyll-sitemap
  # - jekyll-last-modified-at
  - jekyll-archives
last-modified-at:
  date-format: '%B %d %Y'
jekyll-archives:
  enabled:
    - year
    - tags
  layouts:
    year: year
    tag: tag
  permalinks:
    year: /posts/:year/
    tag: /tag/:name/

title: 'Knights of Columbus: Alhambra Council #2431'
description: 'The Alhambra Council 2431 has been proud to support the Catholic parishes and local community in Alhambra for 100 years. We are currently supporting the parishes of St. Therese, St. Thomas More, and All Souls.'
council-tagline: 'Working as one in service to many'

collections:
  events:
    output: true
    permalink: /events/:path/

council_name: 'Alhambra'
council_email: 'kofc2431@yahoo.com'
council_number: 2431
url: https://www.kofc2431.org
events_date_format: '%B %d, %Y'
events_time_format: '%-I:%M %p'
posts_date_format: '%B %d, %Y'
timezone: US/Pacific
council_calendar_feed: 'https://secure.kofc2431.org/council/2431/events/feed'
topbar:
  show_kofc_logo: True
  show_council_name: True
  show_council_number: False
  show_knights_of_columbus_text: True
  custom_text: 'Top bar text example'
  use_custom_text: False
layout:
  w_desktop_width: 60
council_logo_url: '/assets/svg/council-light.svg'
homepage:
  events:
    show_section: True
  parishes:
    show_section: True
    show_sentence: False
    show_parish_map: True
    show_parish_list: True
    parish_map_type: 'interactive'
    # parish_map_type: 'static'
    static_map_url: 
      avif: 'https://2431ocpstorage.blob.core.windows.net/production-anonymous-container/2431/map_images/Alhambra_google_maps_static_map.avif'
      jpg:  'https://2431ocpstorage.blob.core.windows.net/production-anonymous-container/2431/map_images/Alhambra_google_maps_static_map.jpg'

snow_effect:
  enabled: True
  start_date: 'December 1'
  end_date: 'January 31'